application: matsumoto26sunday
version: 5
runtime: python27
api_version: 1
threadsafe: false


libraries:
- name: lxml
  version: "2.3"

inbound_services:
- mail


handlers:

- url: /helper/tally
  script: tally.py
  login: admin

- url: /_ah/mail/.+
  script: controllers/mails.py
  login: admin

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /help-upload/scripts/helper.js
  static_files: views/scripts/helper.js
  upload: views/scripts/helper.js

- url: .*
  script: main.py