application: matsumoto26sunday
version: 5
runtime: python27
api_version: 1
threadsafe: false


libraries:
- name: lxml
  version: "2.3"
- name: webapp2
  version: latest


inbound_services:
- mail


handlers:

- url: /helper/tallies
  script: controllers/tallies.py
  login: admin

- url: /_ah/mail/.+
  script: controllers/mails.py
  login: admin

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /api/v1/.*
  script: main_v1.application

- url: .*
  script: main.py
